<?php

namespace AppBundle\Repository;

/**
 * PonyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PonyRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByFilter(array $criteres)
    {

        $qb = $this->getEntityManager()->createQueryBuilder('p');
        $qb
            ->select('p')
            ->from('AppBundle:Pony', 'p');
        if (!empty($criteres['livingAt'])) {
            $qb
                ->orWhere(
                    $qb->expr()->andX('p.bornAt <= :livingAt', 'p.deadAt >= :livingAt'),
                    $qb->expr()->andX('p.bornAt <= :livingAt', 'p.deadAt IS NULL'),
                    $qb->expr()->andX('p.bornAt IS NULL', 'p.deadAt >= :livingAt')
                )
                ->setParameter('livingAt', $criteres['livingAt'])
            ;
        }
        unset($criteres['livingAt']);

        foreach($criteres as $nom => $valeur) {
            if (!empty($valeur)) {
                $qb
                    ->andWhere($qb->expr()->eq('p.' . $nom, ':' . $nom))
                    ->setParameter($nom, $valeur);
            }
        }

        return $qb->getQuery()->getResult();
    }
}
